{
 "title": "finance_driver_ledger",
 "description": "Application",
 "time": { "from": "2019-11-11T09:16:54.476Z", "to": "2019-12-13T09:16:54.476Z" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "label_values(instance)" },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{job=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{job=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   },
   { "name": "application", "label": "Application", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "kafka latency",
   "type": "graph",
   "description": "latency since kafka produced to application consumed",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(Kafka_latency_damitha_seconds_max{job=\"$application\", instance=\"$instance\"})*1000",
     "legendFormat": "{{api}}-{{instance}}"
    }
   ]
  },
  {
   "title": "kafka-queue latency",
   "type": "graph",
   "description": "latency since kafka produced to application consumed",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(kafka_queue_latency_damitha_seconds_max{job=\"$application\", instance=\"$instance\"})*1000",
     "legendFormat": "{{api}}-{{instance}}"
    }
   ]
  },
  {
   "title": "total process",
   "type": "graph",
   "description": "latency since kafka produced to application consumed",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(Total_process_time_damitha_seconds_max{job=\"$application\", instance=\"$instance\"})*1000",
     "legendFormat": "{{api}}-{{instance}}"
    }
   ]
  },
  {
   "title": "tomcat thread percentage(current/max)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(tomcat_threads_current_threads/tomcat_threads_config_max_threads{job=\"$application\", instance=\"$instance\"})*100"
    }
   ]
  },
  {
   "title": "system cpu usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"$application\", instance=\"$instance\"}"
    },
    {
     "expr": "process_cpu_usage{job=\"$application\",instance=\"$instance\"}"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{job=\"$application\",instance=\"$instance\"}[1h])"
    }
   ]
  },
  {
   "title": "Active jdbc connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "expr": "jdbc_connections_active{job=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "open file descriptors(current/max)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(process_files_open_files/process_files_max_files{job=\"$application\", instance=\"$instance\"})*100"
    }
   ]
  },
  {
   "title": "Application up time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "(process_uptime_seconds{job=\"$application\", instance=\"$instance\"}/86400)"
    }
   ]
  },
  {
   "title": "System cpu count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "system_cpu_count{job=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Error Frequency",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "targets": [
    {
     "expr": "rate(log4j2_events_total{job=\"$application\", instance=\"$instance\",level=\"error\"}[30m])"
    }
   ]
  },
  {
   "title": "Event consuming rate",
   "type": "graph",
   "description": "Queue popup rate",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Event_consuming_rate_damitha_total{job=\"$application\", instance=\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Jvm Thread states",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}-{{state}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 25 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$application\",instance=\"$instance\",area=\"heap\"})*100/sum(jvm_memory_max_bytes{job=\"$application\",instance=\"$instance\",area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 25 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$application\",instance=\"$instance\",area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{job=\"$application\",instance=\"$instance\",area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$application\",instance=\"$instance\",area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$application\",instance=\"$instance\",area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$application\",instance=\"$instance\",area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$application\", instance=\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$application\", instance=\"$instance\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$application\", instance=\"$instance\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "GC collections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{job=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "GC Pause Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{job=\"$application\", instance=\"$instance\"}[1m])/rate(jvm_gc_pause_seconds_count{job=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "GC Allocated/Promoted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{job=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "promoted"
    }
   ]
  }
 ]
}